# ============================================
# SpaceUp - SonarQube Configuration
# ============================================
sonar.projectKey=spaceup
sonar.projectName=SpaceUp
sonar.projectVersion=1.0.0

# Código fuente real del repo
sonar.sources=SpaceUpBackend/src,SpaceUpWeb/src

# Exclusiones generales
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.spec.ts,\
  **/*.test.ts,\
  **/*.spec.js,\
  **/*.test.js,\
  SpaceUpBackend/src/database/seeds/**,\
  SpaceUpBackend/src/**/*.entity.ts

# Cobertura
sonar.javascript.lcov.reportPaths=SpaceUpBackend/coverage/lcov.info,SpaceUpWeb/coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
