# ============================================
# SpaceUp - SonarQube Configuration
# ============================================
sonar.projectKey=spaceup
sonar.projectName=SpaceUp Admin
sonar.projectVersion=1.0.0

# Fuentes
sonar.sources=SpaceUpBackend/src,SpaceUpWeb/src

# Exclusiones
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.spec.ts,\
  **/*.test.ts,\
  **/test/**,\
  SpaceUpBackend/src/database/seeds/**,\
  SpaceUpBackend/src/**/*.entity.ts

# Lenguajes
sonar.typescript.lcov.reportPaths=SpaceUpWeb/coverage/lcov.info
sonar.javascript.lcov.reportPaths=SpaceUpBackend/coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
